## Решение систем линейных уравнений матричным методом 

$$
\left\{\begin{array}\\
    x_1 - x_2 + 2x_3 = 4\\
    x_1 + 5x_2 - 4x_3 = -3\\
    x_1 - 8x2 - 7x_3 = 6
    \end{array}
    \right.
$$
    

In [10]:
import numpy as np

In [20]:
A = np.matrix('1 -1 2; 1 5 -4; 1 -8 -7')
B = np.matrix('4; -3; 6')
print(A)

[[ 1 -1  2]
 [ 1  5 -4]
 [ 1 -8 -7]]


In [21]:
print(B)

[[ 4]
 [-3]
 [ 6]]


In [22]:
print(np.linalg.det(A))

-95.99999999999999


#### Определитель не равняется 0, следовательно, для этой системы подходит метод решения обратной матрицей

#### Находим обратную матрицу

In [23]:
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.69791667  0.23958333  0.0625    ]
 [-0.03125     0.09375    -0.0625    ]
 [ 0.13541667 -0.07291667 -0.0625    ]]


#### Решение системы линейных алгебраических уравнений матричным методом определяется по формуле $$ X = A^{-1} * B $$

In [24]:
X = A_inv.dot(B)
print(X)

[[ 2.44791667]
 [-0.78125   ]
 [ 0.38541667]]


In [25]:
print("x1 = ", X[0])
print("x2 = ", X[1])
print("x3 = ", X[2])

x1 =  [[2.44791667]]
x2 =  [[-0.78125]]
x3 =  [[0.38541667]]


## Решение систем линейных уравнений методом Крамера

In [39]:
a1 = [1, 1, 1]
a2 = [-1, 5, -8]
a3 = [2, -4, -7]
b = [4, -3, 6]

In [41]:
A = np.transpose(np.matrix([a1, a2, a3]))
print(A)

[[ 1 -1  2]
 [ 1  5 -4]
 [ 1 -8 -7]]


In [42]:
B = np.transpose(np.matrix([b]))
print(B)

[[ 4]
 [-3]
 [ 6]]


#### Определяем вспомогательные матрицы

In [43]:
A1 = np.transpose(np.matrix([b, a2, a3]))
print(A1)

[[ 4 -1  2]
 [-3  5 -4]
 [ 6 -8 -7]]


In [44]:
A2 = np.transpose(np.matrix([a1, b, a3]))
print(A2)

[[ 1  4  2]
 [ 1 -3 -4]
 [ 1  6 -7]]


In [45]:
A3 = np.transpose(np.matrix([a1, a2, b]))
print(A3)

[[ 1 -1  4]
 [ 1  5 -3]
 [ 1 -8  6]]


#### Находим определители главной и вспомогательной матриц

In [46]:
A_det = round(np.linalg.det(A))
A1_det = round(np.linalg.det(A1))
A2_det = round(np.linalg.det(A2))
A3_det = round(np.linalg.det(A3))
print("|A| = ", A_det)
print("|A1| = ", A1_det)
print("|A2| = ", A2_det)
print("|A3| = ", A3_det)

|A| =  -96
|A1| =  -235
|A2| =  75
|A3| =  -37


In [47]:
x1 = A1_det / A_det
x2 = A2_det / A_det
x3 = A3_det / A_det
print("x1 = ", x1)
print("x2 = ", x2)
print("x3 = ", x3)

x1 =  2.4479166666666665
x2 =  -0.78125
x3 =  0.3854166666666667
